services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BACKEND_DOMAIN=${BACKEND_DOMAIN}
      - BACKEND_SCHEME=${BACKEND_SCHEME:-https}
      - ALLOWED_IPS=${ALLOWED_IPS}
    ports:
      - "8080:80"
    restart: unless-stopped
